from __future__ import annotations

# Two-piece refillable screw-together capsule pill (size "0", ~21.7 mm long).
# The red CAP screws onto the white BODY via a helical thread collar at the
# seam.  Rotating the cap around the capsule long axis (X) unscrews it ->
# REVOLUTE joint.

import math

import cadquery as cq

from sdk import (
    ArticulatedObject,
    ArticulationType,
    Box,
    Inertial,
    MotionLimits,
    Origin,
    TestContext,
    TestReport,
    mesh_from_cadquery,
)

# ---------------------------------------------------------------------------
# Real-world dimensions (meters).  Roughly a pharmaceutical "size 0" capsule.
# ---------------------------------------------------------------------------
BODY_OUTER_R = 0.00370          # white body outer radius (~7.4 mm dia)
CAP_OUTER_R = 0.00430           # red cap outer radius (larger for thread bore)
WALL = 0.00030                  # gelatin shell wall thickness
CAP_INNER_R = CAP_OUTER_R - WALL  # 0.00400 – clears body thread ribs

BODY_TUBE_LEN = 0.0118          # white straight tube section
CAP_TUBE_LEN = 0.0058           # red straight tube section

# Thread collar at the seam
THREAD_LEN = 0.0030             # axial engagement length
THREAD_RIB_DEPTH = 0.00025      # radial height of each helical rib
THREAD_RIB_WIDTH = 0.00030      # tangential width of rib cross-section
THREAD_N_STARTS = 2             # 2-start thread
THREAD_N_TURNS = 1              # one full turn over THREAD_LEN

# Ground lift: capsule rests on its largest radius (the red cap).
GROUND_LIFT = CAP_OUTER_R


# ---------------------------------------------------------------------------
# Geometry helpers
# ---------------------------------------------------------------------------

def _shell_half(outer_r: float, tube_len: float, *, name: str) -> object:
    """Build one hollow capsule half: open-mouth tube closed by a hemisphere.

    Local frame: OPEN MOUTH at x=0, tube + dome extend toward +X.
    """
    inner_r = outer_r - WALL

    outer_tube = cq.Workplane("YZ").circle(outer_r).extrude(tube_len)
    outer_dome = (
        cq.Workplane("YZ").workplane(offset=tube_len).sphere(outer_r)
    )
    outer_solid = outer_tube.union(outer_dome)

    inner_tube = (
        cq.Workplane("YZ")
        .circle(inner_r)
        .extrude(tube_len)
        .translate((-WALL, 0.0, 0.0))
    )
    inner_dome = (
        cq.Workplane("YZ").workplane(offset=tube_len).sphere(inner_r)
    )
    inner_cavity = inner_tube.union(inner_dome)

    return outer_solid.cut(inner_cavity)


def _helical_ribs(
    radius: float,
    length: float,
    n_starts: int,
    rib_depth: float,
    rib_width: float,
    n_turns: int,
    *,
    angle_offset_deg: float = 0.0,
) -> object:
    """Create helical thread ribs via twistExtrude along the X axis.

    A small rectangular profile is placed at *radius* in the YZ plane and
    twist-extruded along +X while rotating 360°·n_turns around the X axis.
    Multiple starts are generated by rotating copies around X.

    The result is centered at x=0 (extends from -length/2 to +length/2).
    """
    twist_deg = n_turns * 360.0

    first_rib = (
        cq.Workplane("YZ")
        .center(radius, 0.0)
        .rect(rib_depth, rib_width)
        .twistExtrude(length, twist_deg)
    )

    result = first_rib
    for i in range(1, n_starts):
        angle = angle_offset_deg + i * (360.0 / n_starts)
        rib_copy = first_rib.rotate((0.0, 0.0, 0.0), (1.0, 0.0, 0.0), angle)
        result = result.union(rib_copy)

    # Center at x = 0
    result = result.translate((-length / 2.0, 0.0, 0.0))
    return result


def _thread_collar(
    base_outer_r: float,
    base_inner_r: float,
    rib_radius: float,
    length: float,
    n_starts: int,
    rib_depth: float,
    rib_width: float,
    n_turns: int,
    *,
    angle_offset_deg: float = 0.0,
) -> object:
    """Annular collar base + helical ribs, centered at x=0."""
    collar_base = (
        cq.Workplane("YZ")
        .circle(base_outer_r)
        .circle(base_inner_r)
        .extrude(length)
        .translate((-length / 2.0, 0.0, 0.0))
    )
    ribs = _helical_ribs(
        rib_radius, length, n_starts, rib_depth, rib_width, n_turns,
        angle_offset_deg=angle_offset_deg,
    )
    return collar_base.union(ribs)


def _imprint_82(cap_outer_r: float) -> object:
    """Embossed '82' imprint on the red cap side (post-mirror cap frame)."""
    x_center = -CAP_TUBE_LEN * 0.5
    surf_y = cap_outer_r
    proud = 0.00012
    t = 0.00018
    depth = WALL + proud

    def bar(cx: float, cz: float, lx: float, lz: float) -> cq.Workplane:
        return (
            cq.Workplane("XZ")
            .workplane(offset=surf_y - WALL * 0.5)
            .center(cx, cz)
            .rect(lx, lz)
            .extrude(depth)
        )

    eight_cx = x_center - 0.0013
    ring_w = 0.0013
    parts = [
        bar(eight_cx, 0.0010, ring_w, t),
        bar(eight_cx, 0.0, ring_w, t),
        bar(eight_cx, -0.0010, ring_w, t),
        bar(eight_cx - ring_w / 2 + t / 2, 0.0005, t, 0.0012),
        bar(eight_cx + ring_w / 2 - t / 2, 0.0005, t, 0.0012),
        bar(eight_cx - ring_w / 2 + t / 2, -0.0005, t, 0.0012),
        bar(eight_cx + ring_w / 2 - t / 2, -0.0005, t, 0.0012),
    ]

    two_cx = x_center + 0.0013
    two_w = 0.0013
    parts += [
        bar(two_cx, 0.0010, two_w, t),
        bar(two_cx + two_w / 2 - t / 2, 0.0005, t, 0.0012),
        bar(two_cx, 0.0, two_w, t),
        bar(two_cx - two_w / 2 + t / 2, -0.0005, t, 0.0012),
        bar(two_cx, -0.0010, two_w, t),
    ]

    backing = (
        cq.Workplane("XZ")
        .workplane(offset=surf_y - WALL * 0.65)
        .center(x_center, 0.0)
        .rect(0.0042, 0.0026)
        .extrude(WALL * 0.7)
    )

    glyphs = backing
    for p in parts:
        glyphs = glyphs.union(p)
    glyphs = glyphs.mirror("XZ")
    return glyphs


# ---------------------------------------------------------------------------
# Model
# ---------------------------------------------------------------------------

def build_object_model() -> ArticulatedObject:
    model = ArticulatedObject(name="capsule_pill")

    gel_white = model.material("gelatin_white", rgba=(0.95, 0.95, 0.94, 1.0))
    gel_red = model.material("gelatin_red", rgba=(0.86, 0.10, 0.10, 1.0))
    imprint = model.material("imprint_ink", rgba=(0.78, 0.05, 0.05, 1.0))

    # -- WHITE BODY (root) ---------------------------------------------------
    body = model.part("capsule_body")
    body_shell = _shell_half(BODY_OUTER_R, BODY_TUBE_LEN, name="body")
    body.visual(
        mesh_from_cadquery(body_shell, "body_shell"),
        origin=Origin(xyz=(0.0, 0.0, GROUND_LIFT)),
        material=gel_white,
        name="body_shell",
    )

    # Body thread collar: external helical ribs at the mouth end.
    # The collar base wraps around the body tube near x=0.
    body_collar = _thread_collar(
        base_outer_r=BODY_OUTER_R + 0.00010,   # collar outer (just past body)
        base_inner_r=BODY_OUTER_R - 0.00030,   # collar inner (inside body wall)
        rib_radius=BODY_OUTER_R + THREAD_RIB_DEPTH * 0.5,  # rib center
        length=THREAD_LEN,
        n_starts=THREAD_N_STARTS,
        rib_depth=THREAD_RIB_DEPTH,
        rib_width=THREAD_RIB_WIDTH,
        n_turns=THREAD_N_TURNS,
    )
    body.visual(
        mesh_from_cadquery(body_collar, "body_thread_collar"),
        origin=Origin(xyz=(0.0, 0.0, GROUND_LIFT)),
        material=gel_white,
        name="body_thread_collar",
    )

    body.inertial = Inertial.from_geometry(
        Box((BODY_TUBE_LEN + BODY_OUTER_R, 2 * BODY_OUTER_R, 2 * BODY_OUTER_R)),
        mass=0.0004,
        origin=Origin(xyz=((BODY_TUBE_LEN + BODY_OUTER_R) / 2.0, 0.0, GROUND_LIFT)),
    )

    # -- RED CAP -------------------------------------------------------------
    cap = model.part("capsule_cap")
    cap_shell = _shell_half(CAP_OUTER_R, CAP_TUBE_LEN, name="cap")
    cap_shell = cap_shell.mirror("YZ")
    cap.visual(
        mesh_from_cadquery(cap_shell, "cap_shell"),
        material=gel_red,
        name="cap_shell",
    )

    # Cap thread collar: internal helical ribs at the mouth end.
    # Phase-offset by half a start angle so the cap ribs sit in body grooves.
    cap_collar = _thread_collar(
        base_outer_r=CAP_INNER_R + 0.00030,    # collar outer (inside cap wall)
        base_inner_r=CAP_INNER_R - 0.00010,    # collar inner (bore surface)
        rib_radius=CAP_INNER_R - THREAD_RIB_DEPTH * 0.5,  # rib center (inner)
        length=THREAD_LEN,
        n_starts=THREAD_N_STARTS,
        rib_depth=THREAD_RIB_DEPTH,
        rib_width=THREAD_RIB_WIDTH,
        n_turns=THREAD_N_TURNS,
        angle_offset_deg=360.0 / (2 * THREAD_N_STARTS),  # half-start offset
    )
    cap.visual(
        mesh_from_cadquery(cap_collar, "cap_thread_collar"),
        material=gel_red,
        name="cap_thread_collar",
    )

    # Embossed "82" imprint on the red cap side.
    imprint_mesh = _imprint_82(CAP_OUTER_R)
    cap.visual(
        mesh_from_cadquery(imprint_mesh, "cap_imprint"),
        material=imprint,
        name="cap_imprint",
    )

    cap.inertial = Inertial.from_geometry(
        Box((CAP_TUBE_LEN + CAP_OUTER_R, 2 * CAP_OUTER_R, 2 * CAP_OUTER_R)),
        mass=0.0003,
        origin=Origin(xyz=(-(CAP_TUBE_LEN + CAP_OUTER_R) / 2.0, 0.0, 0.0)),
    )

    # -- REVOLUTE JOINT (screw thread) ---------------------------------------
    # Axis is the capsule long axis (X).  At q=0 the cap is fully tightened.
    # Positive q unscrews the cap (one full turn = 2π).
    model.articulation(
        "body_to_cap",
        ArticulationType.REVOLUTE,
        parent=body,
        child=cap,
        origin=Origin(xyz=(0.0, 0.0, GROUND_LIFT)),
        axis=(1.0, 0.0, 0.0),
        motion_limits=MotionLimits(
            effort=2.0,
            velocity=1.5,
            lower=0.0,
            upper=2.0 * math.pi,
        ),
    )

    return model


# ---------------------------------------------------------------------------
# Tests
# ---------------------------------------------------------------------------

def run_tests() -> TestReport:
    ctx = TestContext(object_model)

    body = object_model.get_part("capsule_body")
    cap = object_model.get_part("capsule_cap")
    joint = object_model.get_articulation("body_to_cap")

    # --- Mechanism: revolute joint along X axis ----------------------------
    ctx.check(
        "body_to_cap is revolute",
        joint.articulation_type == ArticulationType.REVOLUTE,
        details=f"type={joint.articulation_type}",
    )
    ax = tuple(round(v, 6) for v in joint.axis)
    ctx.check(
        "cap rotates around capsule long axis (X)",
        ax[0] == 1.0 and ax[1] == 0.0 and ax[2] == 0.0,
        details=f"axis={ax}",
    )
    lim = joint.motion_limits
    ctx.check(
        "unscrew range: 0 to ≥π",
        lim is not None and lim.lower == 0.0 and lim.upper is not None and lim.upper >= math.pi,
        details=f"limits=({lim.lower if lim else None},{lim.upper if lim else None})",
    )

    # --- Visual hero parts present -----------------------------------------
    ctx.check(
        "white body shell visual present",
        any(v.name == "body_shell" for v in body.visuals),
        details=str([v.name for v in body.visuals]),
    )
    ctx.check(
        "red cap shell visual present",
        any(v.name == "cap_shell" for v in cap.visuals),
        details=str([v.name for v in cap.visuals]),
    )
    ctx.check(
        "body thread collar visual present",
        any(v.name == "body_thread_collar" for v in body.visuals),
        details=str([v.name for v in body.visuals]),
    )
    ctx.check(
        "cap thread collar visual present",
        any(v.name == "cap_thread_collar" for v in cap.visuals),
        details=str([v.name for v in cap.visuals]),
    )
    ctx.check(
        "embossed 82 imprint present on cap",
        any(v.name == "cap_imprint" for v in cap.visuals),
        details=str([v.name for v in cap.visuals]),
    )

    # --- Intentional overlaps at the screw-thread seam ---------------------
    # Thread ribs interleave between body and cap collars.
    ctx.allow_overlap(
        cap, body,
        elem_a="cap_thread_collar", elem_b="body_thread_collar",
        reason="Helical thread ribs intentionally interleave at the screw seam.",
    )
    # Body collar base embedded in the body shell wall.
    ctx.allow_overlap(
        body, body,
        elem_a="body_thread_collar", elem_b="body_shell",
        reason="Body thread collar base is embedded in the body shell wall at the mouth.",
    )
    # Cap collar base embedded in the cap shell wall.
    ctx.allow_overlap(
        cap, cap,
        elem_a="cap_thread_collar", elem_b="cap_shell",
        reason="Cap thread collar base is embedded in the cap shell wall at the mouth.",
    )
    # Cap collar reaches into the body tube zone at the seam.
    ctx.allow_overlap(
        cap, body,
        elem_a="cap_thread_collar", elem_b="body_shell",
        reason="Cap thread collar extends past the seam into the body tube bore.",
    )
    # Body collar reaches into the cap tube zone at the seam.
    ctx.allow_overlap(
        cap, body,
        elem_a="cap_shell", elem_b="body_thread_collar",
        reason="Body thread collar extends past the seam into the cap bore.",
    )
    # Imprint embedded in cap surface.
    ctx.allow_overlap(
        cap, cap,
        elem_a="cap_imprint", elem_b="cap_shell",
        reason="The 82 imprint is intentionally embedded into the cap surface.",
    )

    # --- Thread collars overlap along X at the seam (screw engagement) -----
    with ctx.pose({joint: 0.0}):
        ctx.expect_overlap(
            cap, body,
            axes="x",
            elem_a="cap_thread_collar", elem_b="body_thread_collar",
            min_overlap=0.001,
            name="thread collars overlap along X at the seam",
        )
        # Thread collars are concentric in YZ
        ctx.expect_overlap(
            cap, body,
            axes="yz",
            elem_a="cap_thread_collar", elem_b="body_thread_collar",
            min_overlap=0.001,
            name="thread collars overlap in YZ (concentric engagement)",
        )

    # --- Revolute joint: rotation does NOT translate the cap ---------------
    with ctx.pose({joint: 0.0}):
        pos_0 = ctx.part_world_position(cap)
    with ctx.pose({joint: math.pi}):
        pos_pi = ctx.part_world_position(cap)

    ctx.check(
        "cap position available at both poses",
        pos_0 is not None and pos_pi is not None,
    )
    if pos_0 is not None and pos_pi is not None:
        dx = abs(pos_pi[0] - pos_0[0])
        dy = abs(pos_pi[1] - pos_0[1])
        dz = abs(pos_pi[2] - pos_0[2])
        ctx.check(
            "revolute joint: cap origin does not translate during rotation",
            dx < 1e-6 and dy < 1e-6 and dz < 1e-6,
            details=f"dx={dx:.2e}, dy={dy:.2e}, dz={dz:.2e}",
        )

    return ctx.report()


object_model = build_object_model()
