from __future__ import annotations

import hashlib
import importlib.util
import json
from pathlib import Path

import pytest


REPO = Path(__file__).resolve().parents[2]
RUNNER = REPO / "exp/scripts/run_urdf_table3_pva_manifest.py"


def load_runner():
    spec = importlib.util.spec_from_file_location("urdf_table3_pva_manifest_test", RUNNER)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def test_formal_contract_freezes_pva_cohort_and_k21() -> None:
    runner = load_runner()
    args = runner.parse_args([])
    runner.validate_contract(args)
    assert args.mode == "formal"
    assert args.limit is None
    assert args.samples == 21
    assert args.workers == 4
    assert args.asset_timeout_seconds == 120.0

    for extra in (
        ["--limit", "2"],
        ["--samples", "20"],
        ["--workers", "1"],
        ["--cohort-manifest", "/tmp/other.json"],
    ):
        with pytest.raises(ValueError, match="formal"):
            runner.validate_contract(runner.parse_args(extra))


def test_formal_loader_binds_all_frozen_assets_and_receipts() -> None:
    runner = load_runner()
    loaded = runner.load_cohort(runner.DEFAULT_COHORT_MANIFEST, formal=True)
    assert len(loaded["assets"]) == runner.FORMAL_N_EVAL
    assert loaded["eval_category_count"] == runner.FORMAL_RELEASE_CATEGORY_COUNT
    assert loaded["n_release"] == runner.FORMAL_N_RELEASE
    assert loaded["table1_manifest_sha256"] == runner.FORMAL_TABLE1_FILE_SHA256
    assert loaded["table2_manifest_sha256"] == runner.FORMAL_TABLE2_FILE_SHA256
    assert loaded["table2_manifest_content_sha256"] == runner.FORMAL_TABLE2_CONTENT_SHA256
    assert loaded["assets"][0]["selection_index"] == 0
    assert loaded["assets"][-1]["selection_index"] == runner.FORMAL_N_EVAL - 1


def test_smoke_output_has_full_binding_and_artifact_receipt() -> None:
    output = REPO / "exp/runtime/urdf_table3_pva_smoke_check"
    if not output.is_dir():
        pytest.skip("smoke output is generated by the smoke validation command")
    manifest = json.loads((output / "manifest.json").read_text(encoding="utf-8"))
    summary = json.loads((output / "summary.json").read_text(encoding="utf-8"))
    artifact = json.loads((output / "artifact_manifest.json").read_text(encoding="utf-8"))
    rows = [json.loads(line) for line in (output / "asset_records.jsonl").read_text().splitlines()]
    assert manifest["manifest_content_sha256"] == runner_self_hash(manifest)
    assert summary["n_eval"] == len(rows) == 2
    assert summary["metrics"]["strict_kinematic_pass"]["denominator"] == 2
    assert summary["metrics"]["fk_roundtrip_error"]["status"] == "COMPLETE"
    assert set(artifact["files"]) == {
        "manifest.json",
        "asset_records.jsonl",
        "summary.json",
        "summary.md",
        "timing.json",
    }
    for name, binding in artifact["files"].items():
        path = output / name
        assert path.stat().st_size == binding["bytes"]
        assert hashlib.sha256(path.read_bytes()).hexdigest() == binding["sha256"]


def runner_self_hash(manifest: dict[str, object]) -> str:
    body = dict(manifest)
    body.pop("manifest_content_sha256", None)
    payload = json.dumps(body, sort_keys=True, separators=(",", ":"), ensure_ascii=True).encode()
    return hashlib.sha256(payload).hexdigest()
